#ifndef CONFIG_h_
#define CONFIG_h_

#define SYSTIME_TIMERS      5

#define CONSOLE_CMD_ARGS    10
#define CONSOLE_CMD_OUTBUF  500

#define CONSOLE_TELNET_TIMEOUT (5*60)
#define CONSOLE_SESSION_NUM 1

#define CONSOLE_DMESG_BUFFER (424)
#define CONSOLE_CMD_BUFFER  100

#define CONSOLE_HAVE_DMESG  0
#define CONSOLE_HAVE_TELNET 0
#define CONSOLE_HAVE_THREAD 0



#endif
